name: Run secrets.py with GitHub Secrets

on: [push, pull_request]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: (Optional) Create .env file from GitHub Secrets
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Run secrets.py script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python secrets.py
